# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.account_type_enum import AccountTypeEnum

class TestAccountTypeEnum(unittest.TestCase):
    """AccountTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountTypeEnum(self):
        """Test AccountTypeEnum"""
        # inst = AccountTypeEnum()

if __name__ == '__main__':
    unittest.main()
