# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.transaction_resource_attributes import TransactionResourceAttributes

class TestTransactionResourceAttributes(unittest.TestCase):
    """TransactionResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionResourceAttributes:
        """Test TransactionResourceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionResourceAttributes`
        """
        model = TransactionResourceAttributes()
        if include_optional:
            return TransactionResourceAttributes(
                status = 'HELD',
                raw_text = '',
                description = '',
                message = '',
                is_categorizable = True,
                hold_info = None,
                round_up = None,
                cashback = None,
                amount = upbank_spec.models.money_object.MoneyObject(
                    currency_code = '', 
                    value = '', 
                    value_in_base_units = 56, ),
                foreign_amount = None,
                settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TransactionResourceAttributes(
                status = 'HELD',
                raw_text = '',
                description = '',
                message = '',
                is_categorizable = True,
                hold_info = None,
                round_up = None,
                cashback = None,
                amount = upbank_spec.models.money_object.MoneyObject(
                    currency_code = '', 
                    value = '', 
                    value_in_base_units = 56, ),
                foreign_amount = None,
                settled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testTransactionResourceAttributes(self):
        """Test TransactionResourceAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
