# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upbank_spec.api.utility_endpoints_api import UtilityEndpointsApi


class TestUtilityEndpointsApi(unittest.TestCase):
    """UtilityEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UtilityEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_util_ping_get(self) -> None:
        """Test case for util_ping_get

        Ping
        """
        pass


if __name__ == '__main__':
    unittest.main()
