# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.webhook_delivery_log_resource_attributes import WebhookDeliveryLogResourceAttributes

class TestWebhookDeliveryLogResourceAttributes(unittest.TestCase):
    """WebhookDeliveryLogResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryLogResourceAttributes:
        """Test WebhookDeliveryLogResourceAttributes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryLogResourceAttributes`
        """
        model = WebhookDeliveryLogResourceAttributes()
        if include_optional:
            return WebhookDeliveryLogResourceAttributes(
                request = upbank_spec.models.webhook_delivery_log_resource_attributes_request.WebhookDeliveryLogResource_attributes_request(
                    body = '', ),
                response = upbank_spec.models.webhook_delivery_log_resource_attributes_response.WebhookDeliveryLogResource_attributes_response(
                    status_code = 56, 
                    body = '', ),
                delivery_status = 'DELIVERED',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WebhookDeliveryLogResourceAttributes(
                request = upbank_spec.models.webhook_delivery_log_resource_attributes_request.WebhookDeliveryLogResource_attributes_request(
                    body = '', ),
                response = upbank_spec.models.webhook_delivery_log_resource_attributes_response.WebhookDeliveryLogResource_attributes_response(
                    status_code = 56, 
                    body = '', ),
                delivery_status = 'DELIVERED',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testWebhookDeliveryLogResourceAttributes(self):
        """Test WebhookDeliveryLogResourceAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
