# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.webhook_event_callback import WebhookEventCallback

class TestWebhookEventCallback(unittest.TestCase):
    """WebhookEventCallback unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEventCallback:
        """Test WebhookEventCallback
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEventCallback`
        """
        model = WebhookEventCallback()
        if include_optional:
            return WebhookEventCallback(
                data = upbank_spec.models.webhook_event_resource.WebhookEventResource(
                    type = '', 
                    id = '', 
                    attributes = upbank_spec.models.webhook_event_resource_attributes.WebhookEventResource_attributes(
                        event_type = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    relationships = upbank_spec.models.webhook_event_resource_relationships.WebhookEventResource_relationships(
                        webhook = upbank_spec.models.webhook_event_resource_relationships_webhook.WebhookEventResource_relationships_webhook(
                            data = upbank_spec.models.webhook_event_resource_relationships_webhook_data.WebhookEventResource_relationships_webhook_data(
                                type = '', 
                                id = '', ), 
                            links = upbank_spec.models.account_resource_relationships_transactions_links.AccountResource_relationships_transactions_links(
                                related = '', ), ), 
                        transaction = upbank_spec.models.webhook_event_resource_relationships_transaction.WebhookEventResource_relationships_transaction(
                            data = upbank_spec.models.webhook_event_resource_relationships_transaction_data.WebhookEventResource_relationships_transaction_data(
                                type = '', 
                                id = '', ), ), ), )
            )
        else:
            return WebhookEventCallback(
                data = upbank_spec.models.webhook_event_resource.WebhookEventResource(
                    type = '', 
                    id = '', 
                    attributes = upbank_spec.models.webhook_event_resource_attributes.WebhookEventResource_attributes(
                        event_type = null, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    relationships = upbank_spec.models.webhook_event_resource_relationships.WebhookEventResource_relationships(
                        webhook = upbank_spec.models.webhook_event_resource_relationships_webhook.WebhookEventResource_relationships_webhook(
                            data = upbank_spec.models.webhook_event_resource_relationships_webhook_data.WebhookEventResource_relationships_webhook_data(
                                type = '', 
                                id = '', ), 
                            links = upbank_spec.models.account_resource_relationships_transactions_links.AccountResource_relationships_transactions_links(
                                related = '', ), ), 
                        transaction = upbank_spec.models.webhook_event_resource_relationships_transaction.WebhookEventResource_relationships_transaction(
                            data = upbank_spec.models.webhook_event_resource_relationships_transaction_data.WebhookEventResource_relationships_transaction_data(
                                type = '', 
                                id = '', ), ), ), ),
        )
        """

    def testWebhookEventCallback(self):
        """Test WebhookEventCallback"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
