# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upbank_spec.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_tags_get(self) -> None:
        """Test case for tags_get

        List tags
        """
        pass

    def test_transactions_transaction_id_relationships_tags_delete(self) -> None:
        """Test case for transactions_transaction_id_relationships_tags_delete

        Remove tags from transaction
        """
        pass

    def test_transactions_transaction_id_relationships_tags_post(self) -> None:
        """Test case for transactions_transaction_id_relationships_tags_post

        Add tags to transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
