# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upbank_spec.api.transactions_api import TransactionsApi


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionsApi()

    def tearDown(self) -> None:
        pass

    def test_accounts_account_id_transactions_get(self) -> None:
        """Test case for accounts_account_id_transactions_get

        List transactions by account
        """
        pass

    def test_transactions_get(self) -> None:
        """Test case for transactions_get

        List transactions
        """
        pass

    def test_transactions_id_get(self) -> None:
        """Test case for transactions_id_get

        Retrieve transaction
        """
        pass


if __name__ == '__main__':
    unittest.main()
