# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.webhook_event_resource_relationships_transaction import WebhookEventResourceRelationshipsTransaction

class TestWebhookEventResourceRelationshipsTransaction(unittest.TestCase):
    """WebhookEventResourceRelationshipsTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookEventResourceRelationshipsTransaction:
        """Test WebhookEventResourceRelationshipsTransaction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookEventResourceRelationshipsTransaction`
        """
        model = WebhookEventResourceRelationshipsTransaction()
        if include_optional:
            return WebhookEventResourceRelationshipsTransaction(
                data = upbank_spec.models.webhook_event_resource_relationships_transaction_data.WebhookEventResource_relationships_transaction_data(
                    type = '', 
                    id = '', ),
                links = upbank_spec.models.account_resource_relationships_transactions_links.AccountResource_relationships_transactions_links(
                    related = '', )
            )
        else:
            return WebhookEventResourceRelationshipsTransaction(
                data = upbank_spec.models.webhook_event_resource_relationships_transaction_data.WebhookEventResource_relationships_transaction_data(
                    type = '', 
                    id = '', ),
        )
        """

    def testWebhookEventResourceRelationshipsTransaction(self):
        """Test WebhookEventResourceRelationshipsTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
