# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.webhook_delivery_log_resource_relationships_webhook_event import WebhookDeliveryLogResourceRelationshipsWebhookEvent

class TestWebhookDeliveryLogResourceRelationshipsWebhookEvent(unittest.TestCase):
    """WebhookDeliveryLogResourceRelationshipsWebhookEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryLogResourceRelationshipsWebhookEvent:
        """Test WebhookDeliveryLogResourceRelationshipsWebhookEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryLogResourceRelationshipsWebhookEvent`
        """
        model = WebhookDeliveryLogResourceRelationshipsWebhookEvent()
        if include_optional:
            return WebhookDeliveryLogResourceRelationshipsWebhookEvent(
                data = upbank_spec.models.webhook_delivery_log_resource_relationships_webhook_event_data.WebhookDeliveryLogResource_relationships_webhookEvent_data(
                    type = '', 
                    id = '', )
            )
        else:
            return WebhookDeliveryLogResourceRelationshipsWebhookEvent(
                data = upbank_spec.models.webhook_delivery_log_resource_relationships_webhook_event_data.WebhookDeliveryLogResource_relationships_webhookEvent_data(
                    type = '', 
                    id = '', ),
        )
        """

    def testWebhookDeliveryLogResourceRelationshipsWebhookEvent(self):
        """Test WebhookDeliveryLogResourceRelationshipsWebhookEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
