# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.round_up_object import RoundUpObject

class TestRoundUpObject(unittest.TestCase):
    """RoundUpObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RoundUpObject:
        """Test RoundUpObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RoundUpObject`
        """
        model = RoundUpObject()
        if include_optional:
            return RoundUpObject(
                amount = upbank_spec.models.money_object.MoneyObject(
                    currency_code = '', 
                    value = '', 
                    value_in_base_units = 56, ),
                boost_portion = None
            )
        else:
            return RoundUpObject(
                amount = upbank_spec.models.money_object.MoneyObject(
                    currency_code = '', 
                    value = '', 
                    value_in_base_units = 56, ),
                boost_portion = None,
        )
        """

    def testRoundUpObject(self):
        """Test RoundUpObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
