# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from upbank_spec.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_webhooks_get(self) -> None:
        """Test case for webhooks_get

        List webhooks
        """
        pass

    def test_webhooks_id_delete(self) -> None:
        """Test case for webhooks_id_delete

        Delete webhook
        """
        pass

    def test_webhooks_id_get(self) -> None:
        """Test case for webhooks_id_get

        Retrieve webhook
        """
        pass

    def test_webhooks_post(self) -> None:
        """Test case for webhooks_post

        Create webhook
        """
        pass

    def test_webhooks_webhook_id_logs_get(self) -> None:
        """Test case for webhooks_webhook_id_logs_get

        List webhook logs
        """
        pass

    def test_webhooks_webhook_id_ping_post(self) -> None:
        """Test case for webhooks_webhook_id_ping_post

        Ping webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
