# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.ownership_type_enum import OwnershipTypeEnum

class TestOwnershipTypeEnum(unittest.TestCase):
    """OwnershipTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOwnershipTypeEnum(self):
        """Test OwnershipTypeEnum"""
        # inst = OwnershipTypeEnum()

if __name__ == '__main__':
    unittest.main()
