# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from upbank_spec.models.ping_response import PingResponse

class TestPingResponse(unittest.TestCase):
    """PingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PingResponse:
        """Test PingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PingResponse`
        """
        model = PingResponse()
        if include_optional:
            return PingResponse(
                meta = upbank_spec.models.ping_response_meta.PingResponse_meta(
                    id = '', 
                    status_emoji = '', )
            )
        else:
            return PingResponse(
                meta = upbank_spec.models.ping_response_meta.PingResponse_meta(
                    id = '', 
                    status_emoji = '', ),
        )
        """

    def testPingResponse(self):
        """Test PingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
