version: '3'
# TODO: abstract package name

tasks:
  getspec:
    cmds:
      - wget -O ./openapi.json https://raw.githubusercontent.com/up-banking/api/master/v1/openapi.json

      # if spec is json, convert to yaml
      - | 
        docker run --rm \
        -v $PWD:/src \
        mikefarah/yq:4 \
        -p json /src/openapi.json \
        -o yaml > ./openapi.yaml

      - rm ./openapi.json

      - diff -u ./openapi.yaml ./contract-patches/Add_page-after_field.patch || true
      - patch -u -b ./openapi.yaml -i ./contract-patches/Add_page-after_field.patch
    silent: true

  buildspec:
    cmds:
      - | 
        docker run --rm \
        -v $PWD/openapi.yaml:/openapi.yaml:ro \
        -v $PWD/spec/:/spec \
        openapitools/openapi-generator-cli:v7.2.0 generate \
        -i /openapi.yaml \
        -g python \
        -o /spec \
        --package-name upbank_spec \
        --additional-properties=generateSourceCodeOnly=false \
        --additional-properties=packageName=upbank_spec \
        --additional-properties=library=asyncio
    silent: true
    desc: Builds the CDS Banking API client

  lint:
    cmds:
      - poetry run mypy src/
      - poetry run black src/
      - poetry run flake8 src/

  replacemodels:
    cmds:
      - sed -n '/import models into model package/,$p' spec/upbank_spec/models/__init__.py > all_imports.txt
      - sed -i '/BEGIN/,/END/{//!d}' src/upbank_client/models/__init__.py
      - sed -i '/BEGIN/r all_imports.txt' src/upbank_client/models/__init__.py
      - sed -i -E 's/upbank_spec\.models\.[a-zA-Z0-9_]+/upbank_client.models/g' spec/upbank_spec/api/*.py

  updateall:
    deps: [ getspec, buildspec, replacemodels ]