# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AccountTypeEnum(str, Enum):
    """
    Specifies the type of bank account. Currently returned values are `SAVER` and `TRANSACTIONAL`. 
    """

    """
    allowed enum values
    """
    SAVER = 'SAVER'
    TRANSACTIONAL = 'TRANSACTIONAL'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


