# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WebhookDeliveryStatusEnum(str, Enum):
    """
    Specifies the nature of the success or failure of a webhook delivery attempt to the subscribed webhook URL. The currently returned values are described below:  - **`DELIVERED`**: The event was delivered to the webhook URL   successfully and a `200` response was received. - **`UNDELIVERABLE`**: The webhook URL was not reachable, or timed out. - **`BAD_RESPONSE_CODE`**: The event was delivered to the webhook URL   but a non-`200` response was received. 
    """

    """
    allowed enum values
    """
    DELIVERED = 'DELIVERED'
    UNDELIVERABLE = 'UNDELIVERABLE'
    BAD_RESPONSE_CODE = 'BAD_RESPONSE_CODE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookDeliveryStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


