# coding: utf-8

"""
    Up API

    The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class WebhookEventTypeEnum(str, Enum):
    """
    Specifies the type of a webhook event. This can be used to determine what action to take in response to the event, such as which relationships to expect. 
    """

    """
    allowed enum values
    """
    TRANSACTION_CREATED = 'TRANSACTION_CREATED'
    TRANSACTION_SETTLED = 'TRANSACTION_SETTLED'
    TRANSACTION_DELETED = 'TRANSACTION_DELETED'
    PING = 'PING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEventTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


